### ISSUE TITLE
διάγω : proposition de traduction

### ISSUE THREAD

**Issue by kylak** [nouveautestament/nouveautestament.github.io#1]
https://nouveautestament.github.io/lemme/%CE%B4%CE%B9%CE%AC%CE%B3%CF%89.html

Proposition :

- **trans**mener (https://fr.wikisource.org/wiki/Page:Godefroy_-_Lexique_(6).djvu/185)
- **di**riger
- **tra**îner
- **par**courir
- **tra**verser
- **trans**porter

(J'aimer bien transmener.)

Proposition : Donner le pour, le contre de chaque.

**Comment by kylak** [comment]
Ca me paraît vraiment nickel "transmener".

**Comment by nouveautestament** [comment]
[image: image.png]

**Comment by nouveautestament** [comment]
ἄγω [ᾰ] (f. ἄξω, ao.2 ἤγαγον [ᾰ], rar. ao.1 ἦξα, pf. ἦχα : pass. f.
ἀχθήσομαι ou ἄξομαι, ao. ἤχθην, pf. ἦγμαι) :

*A tr.I* mener, conduire :
*1* en gén. (p. opp. à φέρειν) : δῶκε δ' ἄγειν γυναῖκα καὶ τρίποδα φέρειν,
IL. 23, 512, il donna la femme à conduire et le trépied à porter ; ἄγ.
ὑποζύγια, XÉN. An. 4, 5, 24 ; ἵππους, XÉN. Eq. 6, 4, conduire des bêtes de
somme, des chevaux ; βοῦν ἄγ. κεράων, OD. 3, 439 ; ἄγ. ἵππον τῆς ἡνίας,
XÉN. Eq. 6, 9, conduire un bœuf par les cornes, un cheval par la bride ;
avec double acc. : ἄγ. τὸ στράτευμα τὴν ἐπὶ Μέγαρα (s.-e. ὁδόν) XÉN. Hell.
4, 4, 13, diriger l’armée par la route de Mégare ; avec l’idée de « route »
pour suj. : ὁδὸς ἄγει εἰς, acc. SOPH. O.R. 734, la route conduit vers ; cf.
PLAT. Rsp. 435d ; fig. διὰ πόνων ἄγ. τινά, EUR. I.T. 998, conduire qqn à
travers des épreuves ; avec un suj. de chose : ποῖ ἡ ἐπιθυμία αὐτὸν ἄξει ;
PLAT. Rsp. 359e, où le conduira le désir ?.
*2* guider : τινά, EUR. I.T. 988, etc. qqn ; abs. τὰ ἴχνη ἄξει, XÉN. Cyn.
8, 4, les traces guideront ; fig. ἄγεσθαι λογισμῷ, PLAT. Rsp. 431c, être
guidé pur le raisonnement.
*3* p. suite (avec l’idée d’autorité) diriger, gouverner, commander : ἄγ.
στρατιάν, ναῦς, THC. 7, 12 ; 8, 59, etc. ; στρατόν, SOPH. O.C. 1327 ; XÉN.
Cyr. 1, 4, 17, diriger une expédition, une flotte, une armée ; πόλιν, PLAT.
Leg. 771b ; τὴν πολιτείαν, THC. 1, 127, gouverner une cité, l’État ; avec
un suj. de chose : ψυχὴ ἄγει πάντα, PLAT. Leg. 896e, l’âme dirige tout ;
abs. ἄρχειν καὶ ἄγειν, PLAT. Phædr. 237d, commander et gouverner ; ἄγει ὁ
θεὸς οὕτως, XÉN. An. 6, 1, 18, ainsi le veut la divinité.
*4* fig. en parl. d’éducation, diriger, élever, former : παῖδας ἄγειν, LUC.
Anach. 20, élever des enfants ; ὀρθῶς, καλῶς ou κακῶς ἀχθῆναι, PLAT. Leg.
782d, avoir été honnêtement, bien ou mal élevé.
*II* mener avec soi (amener ou emmener) : κῆρυξ ἦλθεν ἄγων ἀοιδόν, OD. 8,
62, le héraut arriva amenant un aède ; ἄγ. τινὰ μεθ' ἑαυτοῦ, XÉN. Cyr. 5,
4, 38, amener qqn avec soi ; d’où le part. ἄγων = σύν ou μετά : τοὺς
θεράποντας ἄγων, XÉN. An. 3, 3, 2, avec ses serviteurs ; cf. An. 4, 4, 10 ;
5, 4, 2 ; Hell. 3, 4, 10, etc.
*III* mener jusqu’à, d’où :
*1* amener : avec un rég. de pers., de chose personnifiée ou d’animal : ἄγ.
εἰς τόπον, ATT. amener dans un lieu ; poét. avec l’acc. seul. : ἄγ. οἴκους,
ESCHL. Pers. 862, ramener (des hommes) dans leurs foyers ; ὑπὸ ζυγὸν ἄγ.
ἵππους, IL. 5, 731, amener des chevaux sous le joug ; ἄγ. εἰς δικαστήριον,
PLAT. Leg. 928b ; εἰς δίκας ou εἰς τὴν δίκην, XÉN. Mem. 2, 9, 1, etc. ; εἰς
κρίσιν, PLAT. Leg. 856c ; ἐπὶ τοὺς δικαστάς, PLAT. ibid. amener au
tribunal, en justice, devant les juges ; en ce sens ἄγειν abs. PLAT. Leg.
914e, Gorg. 527a ; fig. ἄγ. τὰς ψυχὰς εἰς τὴν ἀρετήν, PLAT. Rsp. 547b,
amener les âmes à la vertu ; εἰς φόβον, POL. 3, 2, 2, à la crainte, à
craindre ; avec un rég. de chose, amener, apporter : ἄγ. δῶρα, XÉN. Cyr. 5,
5, 12, etc. apporter des présents ; ἄγ. ἀγώγιμα, PLAT. Prot. 313d, amener
une cargaison ; avec un suj. de chose : οἶνον νῆες ἄγουσι, IL. 9, 72, les
navires apportent du vin ; νῆες πεζοὺς ἤγαγον, ESCHL. Pers. 553, les
navires amenèrent des combattants de pied ; fig. ἄγ. πῆμα, IL. 24, 547,
amener, càd. causer une douleur ; ἄγ. ὕπνον, SOPH. Ph. 638, apporter ou
procurer le sommeil ; avec un inf. ἡ πεπρωμένη ἄγει θανεῖν, EUR. Hec. 43,
la destinée amène à mourir.
*2* amener à soi, attirer : ὁ Μαγνήσιος λίθος τοὺς δακτυλίους σιδηροῦς
ἄγει, PLAT. Ion 533d, la pierre de Magnésie (l’aimant) attire les anneaux
de fer ; fig. πάντας ἤγαγε δοὺς ἀμνηστίαν, HDN 3, 4, 17, il se les concilia
tous en accordant une amnistie ; en mauv. part, attirer (dans un piège)
EUR. Hec. 1146.
*3* p. suite, faire venir, EUR. I.T. 138.
*IV* emmener :
*1* (sans idée de violence) ἄγ. γυναῖκα, ESCHL. Pr. 558, emmener (chez soi)
une femme (pour l’épouser) (d’ord. en ce sens le Moy., v. ci-dessous).
*2* (avec idée de violence) emporter, entraîner : ἄγ. πάντα, IL. 1, 367,
emporter tout (après le pillage d’une ville) ; ἄγειν λείαν, XÉN. Cyr. 5, 3,
1, emporter du butin ; ἵππους αἰχμαλώτους καὶ ἄνδρας ἄγ. XÉN. Cyr. 4, 3, 1,
emmener prisonniers hommes et chevaux ; ἄγ. εἰς δουλείαν, ESCHN. 1, 62
Baiter-Sauppe, etc. emmener en servitude ; ἄγ. καὶ φέρειν, HDT. 1, 88 ;
XÉN. Cyr. 3, 2, 12 ; ou φέρειν καὶ ἄγειν, XÉN. 3, 2, 2, etc. piller,
dévaster (cf. lat. agere et ferre, LIV. 12, 3, etc.) ; φέρειν καὶ ἄγειν
(mais non ἄγειν καὶ φέρειν) signifie qqf. porter en même temps ou ensemble,
PLAT. Phædr. 279c, Leg. 817a ; XÉN. Cyr. 3, 3, 2, etc. (cf. lat. portari
atque agi, CÆS. B. C. 2, 25) ; ἀγόμεθα καὶ φερόμεθα, EUR. Tr. 1310, nous
sommes ruinés, perdus ; ἄγ. καὶ καίειν, XÉN. Hell. 3, 2, 5, piller et
brûler, saccager.
*3* entraîner avec soi par son poids, d’où peser ; ἄγ. μνᾶν, DÉM. 617, 21 ;
ἄγ. τριακοσίους δαρεικούς, DÉM. 741, 7, peser une mine, 300 dariques ; p.
suite, fig. peser, évaluer, estimer, apprécier (cf. lat. ducere) : θεὸν ἄγ.
τινά, LUC. Gall. 18, regarder qqn comme un dieu ; ἄγ. περὶ πλείστου avec
l’inf. HDT. 9, 7, attacher une extrême importance ; ἐν τιμῇ ἄγ. ATT. ;
ἐντίμως ἄγ. PLAT. Rsp. 528c ; διὰ τιμῆς ἄγ. LUC. Prom. 4, avoir en honneur,
faire cas de, estimer ; τιμιώτερον ἄγ. THC. 8, 81, faire plus de cas de ;
πρόσθεν ἄγ. τινά τινος, EUR. Bacch. 225, préférer une divinité à une autre
; ὡς παρ' οὐδὲν ἄγ. SOPH. Ant. 34, ne faire aucun cas de ; ἐν οὐδεμιῇ μοίρῃ
μεγάλῃ ἄγ. τινά, HDT. 2, 172, ne pas professer une grande estime pour qqn ;
au pass. ἠγόμην δ' ἀνὴρ ἀστῶν μέγιστος, SOPH. O.R. 775, je tenais le
premier rang dans la cité.
*V* mener en avant, pousser devant soi :
*1* au propre : ἄγ. τεῖχος, THC. 6, 99, construire un mur ; ἄγ. ὕδωρ, PLAT.
Leg. 844b ; ὄγμον, THCR. Idyl. 10, 2 ; τάφρον, PLUT. Ages. 39, creuser un
conduit d’eau, un canal, un fossé ; γραμμάς, ARSTT. Top. 1, 1, 6, tracer
des lignes.
*2* avec idée de temps ; ἡμέραν ἄγ. XÉN. Cyr. 7, 1, 7, passer le jour ; cf.
SOPH. El. 266 ; EUR. Cycl. 402 ; p. anal. ἄγ. ἑορτήν, HDT. 1, 147, etc. ;
μυστήρια, XÉN. Hell. 1, 4, 8 ; θυσίας, PLAT. 2 Alc. 148e, célébrer une
fête, des mystères, des sacrifices ; de même, en gén. (avec idée de durée,
de prolongation) ἄγ. σχολήν, PLAT. Theæt. 172b = σχολάζειν, être de loisir
; ἄγ. ἡσυχίαν, XÉN. Hell. 1, 4, 18 = ἡσυχεῖν, être en repos ; ἄγ. εἰρήνην,
XÉN. An. 2, 6, 4, être en paix ; ἄγ. πόλεμον, DÉM. 5, 19 Baiter-Sauppe,
être en guerre ; ἄγ. εὐδαιμονίαν, EUR. Hipp. 750, être heureux ; ἄγ. γέλωθ'
(dev. un esprit rude) SOPH. Aj. 382, rire ; ἄγ. πένθος, LUC. Tim. 22, être
dans le deuil, etc.
*3* p. suite, maintenir, conserver : ἐλευθέραν ἦγε τὴν Ἑλλάδα, DÉM. 120,
17, il maintenait la Grèce libre ; d’où
*4* porter loin, répandre : καί μευ κλέος ἦγον Ἀχαιοί, OD. 5, 311, et les
Grecs auraient répandu ma gloire.
*B* intr. en apparence (s.-e. στρατόν ou ἑαυτόν) se pousser en avant,
s’avancer, d’ord. en parl. d’un chef d’armée : καιρός ἐστιν ἄγ. ἐπὶ τοὺς
πολεμίους, XÉN. Cyr. 3, 3, 46, il est temps de marcher à l’ennemi ; ἦγε
ταχέως, XÉN. An. 4, 1, 17, etc. il s’avançait rapidement ; p. suite, en
parl. des soldats eux-mêmes, ou, en gén., d’une troupe : ταύτῃ ἄξει ὁ
λόχος, XÉN. An. 4, 8, 12, c’est par là que s’avancera la compagnie ; cf.
PLAT. Leg. 701e.
*C* emploi épq. et poét. :
*I* part. : ἄγων est souvent joint à un verbe exprimant un placement, un
don, etc. pour une vive représentation de l’action qui précède le placement
: στῆσε δ' ἄγων (νῆας) IL. 2, 558, il amena les navires et les stationna ;
cf. OD. 1, 130.
*II* impér. : l’impér. équivaut à une sorte d’interj. : v. ἄγε, ἄγετε.
*Moy. ἄγομαι* (f. ἄξομαι, ao.2 ἠγαγόμην [ᾰ], pf. ἦγμαι) :
*I* mener, amener ou emmener pour soi ou avec soi :
*1* en parl. de choses : χρυσόν τε καὶ ἄργυρον οἴκαδ' ἄγ. OD. 10, 35,
emporter dans son pays de l’or et de l’argent ; ἄγ. φορτία, XÉN. Œc. 8, 12,
emporter des marchandises.
*2* particul. avec ou sans γυναῖκα, épouser une femme (litt. l’emmener chez
soi) HDT. 5, 90 ; THC. 8, 21 ; ἄγεσθαι se dit aussi du père qui fait
épouser une femme à son fils, OD. 4, 10 ; HDT. 1, 34 ; 9, 111, etc. ; du
frère qui amène une femme à son frère, OD. 15, 238 ; des amis du fiancé qui
amènent la femme chez son époux, OD. 6, 28.
*3* p. suite, entraîner par son poids, d’où peser, évaluer, estimer :
ἄγεσθαι ἐν τιμῇ, HDT. 1, 134 ; 2, 83, avoir en honneur.
*II* amener ou attirer à soi : ἄγονται ὑφ' ἑαυτὰς τοὺς νεοττούς, ARSTT.
H.A. 9, 1, elles attirent leurs petits sous elles ; fig. ἄγεσθαί τινα
σύμμαχον, XÉN. Cyr. 1, 6, 11, amener qqn dans son alliance ; ἄγεσθαί τι ἐς
χεῖρας, HDT. 1, 126 ; 4, 79, prendre une entreprise en main, s’en charger.
*III* mener en avant, pousser, produire au dehors : διὰ στόμα μῦθον
ἄγεσθαι, IL. 14, 91, litt. ouvrir la bouche et émettre un avis. Pf. ἀγήοχα
seul. en composition. Pf. pass. ἦγμαι au sens moy. JOS. A.J. 18, 9, 5. Fut.
moy. ἄξομαι au sens pass. ESCHL. Ag. 1632 ; PLAT. Rsp. 458 d. Formes épq.
ou dialectales : Act. prés. ind. 3 pl. dor. ἄγοντι, PD. P. 7, 13 ; sbj. 3
sg. ἄγῃσι, OD. 6, 37 ; inf. épq. ἀγέμεν, IL. 7, 420 ; inf. eol. ἄγην,
SAPPH. 1, 19. Impf. dor. ἆγον, PD. P. 9, 123 ; ESCHL. Pers. 863, etc. poét.
ἄγον [ᾰ] IL. 7, 312 ; PD. P. 5, 76 ; 3 duel ἀγέτην [ᾰ] OD. 3, 439. Fut.
ind. 3 pl. dor. ἄξοισι, PD. P. 6, 13 ; inf. épq. ἀξέμεναι, OD. 23, 221, ou
ἀξέμεν, IL. 23, 668. Ao.1 avec formes de fut. ou d’ao.2 : impér. 2 pl. épq.
ἄξετε, IL. 3, 105 ; OD. 14, 414 ; inf. ἀξέμεναι, IL. 23, 50 ; HH. Cer. 443,
ou ἀξέμεν, IL. 23, 111 : 24, 663 ; HH. Ap. 103. Ao.2 dor. ἄγαγον [ᾱᾰ] PD.
O. 2, 51 ; SOPH. Tr. 858 ; THCR. Idyl. 15, 103 ; poét. ἄγαγον [ᾰᾰ] IL. 11,
112 ; 24, 764 ; EUR. I.T. 138 ; sbj. 3 sg. épq. ἀγαγῇσι, IL. 24, 155. Ao.
itér. ἄγεσκον [ᾰ] HDT. 1, 148 ; A.RH. 1, 849. Moy. ao.1 épq. sans augm. 2
pl. ἄξεσθε, IL. 8, 505 (var. ἄξασθε) ; 3 pl. ἄξοντο (var. ἄξαντο) IL. 8,
545. Ao.2 dor. ἀγαγόμην [ᾱᾰ] EUR. Andr. 104 conj. R. indo-europ. *h₂eǵ-,
mener ; cf. ὄγμος, lat. agō, sscr. ájati.

Le mar. 10 janv. 2023 à 15:41, Sébastien Tingting DG ***@***.***> a
écrit :

> [image: image.png]
>

**Comment by nouveautestament** [comment]
διάγω δι·άγω

I (διά, en écartant) :
1 écarter, séparer.

2 avec idée de temps, différer

II (διά, à travers) :
1 **conduire à travers**
