### ISSUE TITLE
Le lemme τουτο (n°5021) ne dvrt pas exister + corrections des traductions des neutres des lemmes 5021 et 1561.

### ISSUE THREAD

**Issue by kylak** [nouveautestament/nouveautestament.github.io#1]
n°5021 : https://nouveautestament.github.io/lemme/τοῦτο.html
n°1561 : https://nouveautestament.github.io/lemme/οὗτος.html

τουτο est une déclinaison de ουτος (c'est la forme neutre du nominatif singulier et de l'accusatif singulier de ουτος).

ουτος est d'ailleurs présent sur la fiche de τουτο, cette forme a donc pour l'instant deux numéros d'attribués : 3676 et 5021, problème.

En revanche τουτο signifie bien "ceci" comme mentionné sur la page du numéro 5021, et non "celui-ci" comme mentionné sur la page de ουτος. "celui-ci" est la traduction de ουτος pas de τουτο, le neutre de ουτος se traduit comme le neutre de sa traduction française (traduction qui est "celui-ci") à savoir donc "ceci" (cf. tableau wiktionnaire).

Pareillement avec ἐκεῖνος (n°1561) : soucis de traduction au niveau du neutre.
"celui-là" est la traduction de ἐκεῖνος pas de ἐκεῖνο, le neutre de ἐκεῖνος (c'est-à-dire "ἐκεῖνο") se traduit comme le neutre de sa traduction française (traduction qui est "celui-là") à savoir donc "cela" ou "ça" (cf. tableau wiktionnaire).

lien du tableau wiktionnaire : https://fr.wiktionary.org/wiki/ceci

**Comment by nouveautestament** [comment]
## οὗτος (oytos)
### ceci, cecis, celui-ci, ceux-ci, celle-ci, celles-ci

## ἐκεῖνος (ekeinos)
### cela, celas, celui-là, ceux-là, celle-là, celles-là
