### ISSUE TITLE
θυμός : proposition de traduction

### ISSUE THREAD

**Issue by kylak** [nouveautestament/nouveautestament.github.io#2]
#### semble proche de la définition du Bailly : <br>
- humeur (voir "humer" : inspirer par les **narines** ; cf. la colère qui est liée en [hébreu](https://biblehub.com/hebrew/639.htm) aux **narines** (d'ailleurs A.Dumont a je pense traduit θυμός par "ardente-fulmination-de-narines" en rapport avec cela))
à noter que : θυμός retranscrit en alphabet latin donne thumos (ou thymos), ce qui est assez proche de humor (racine latine de humeur) ; et qu'en espagnol humo signfie fumée, ce que signifie apparement l'étymologie [dʰuh₂mós](https://fr.wiktionary.org/wiki/fumus#la) de θυμός.<br>
Et je viens de tomber sur cela : https://fr.wiktionary.org/wiki/thymie#fr (cf. aussi la section Dérivés)
#### semble particulièrement étymologiquement proche de θυμός :
- tumulute (qui vient du latin [tumeo](https://fr.wiktionary.org/wiki/tumeo#la) ce dernier qui signifie en deuxième sens selon le wiktionnaire "être en colère")
- tuméfier
- thymie (donc)
- thym (néanmoins, il semblerait que ce mot soit lié à l'autre sens de θυμός qui est "thym")

Sur ce, **je propose pour θυμός : humeur (selon la traduction/interprétation latine [de Jérôme] : souvent dans le N.T dans le sens [E du CNTRL](https://www.cnrtl.fr/definition/humeur))** (ou au pire "mouvements d'humeur", mais je trouve ça moins propre car ça serait catégoriser θυμός au sens E du CNTRL, chose qui ne semble pas aller dans le sens de la définition du Bailly).

Extrait d'exemples du sens E du CNTRL :
"_Cette offre donna de l'humeur à Julien, elle dérangeait sa folie. Pendant tout le souper, que les deux amis préparèrent eux-mêmes comme des héros d'Homère, car Fouqué vivait seul, il montra ses comptes à Julien, et lui prouva combien son commerce de bois présentait d'avantages (Stendhal, Rouge et Noir, 1830, p. 73)._"

"_Je ne puis m'empêcher de concevoir quelque humeur contre notre société si profondément divisée en hommes cultivés et en barbares (Renan, Avenir sc.,1890, p. 322)._"

"_Peut-être avait-elle de l'humeur contre Gaspard même, comme s'il prenait trop bien les choses, qu'il n'y vît jamais qu'une occasion de lutte (Pourrat, Gaspard,1930, p. 200)._" 

(Concernant le latin "ira" (duquel vient "irritation" n'est-ce pas) on peut voir qu'il y a en [ses définitions proposées](https://www.dicolatin.com/Latin/Lemme/0/ira) l'expression "accès de mauvaise humeur" qui revient presque tout le temps. En Apoc 15:7 le latin a iracundiae qui contient dans [la définition](https://gaffiot.fr/#iracundia) "humeur irascible". Dès lors, en traduisant par de tels termes, le latin aurait plutôt opté pour le sens E du CNTRL, "mauvaise humeur", plutôt que pour "humeur" simplement.)

Voir aussi la définition du Bailly de [γλυκυ**θυμία**](https://nouveautestament.github.io/dictionnaire/index.html#γλυκυθυμία) (il y a aussi [γλυκύθυμος](https://nouveautestament.github.io/dictionnaire/index.html#γλυκύθυμος)), [δύσ**θυμος**](https://nouveautestament.github.io/dictionnaire/index.html#%CE%B4%E1%BD%BB%CF%83%CE%B8%CF%85%CE%BC%CE%BF%CF%82), [ῥᾳθυμία](https://nouveautestament.github.io/dictionnaire/index.html#%E1%BF%A5%E1%BE%B3%CE%B8%CF%85%CE%BC%E1%BD%B7%CE%B1) (cf. [ῥᾴ**θυμος**](https://nouveautestament.github.io/dictionnaire/index.html#%E1%BF%A5%E1%BE%B4%CE%B8%CF%85%CE%BC%CE%BF%CF%82))

Comment expliquer que les traductions françaises n'aient pas "humeur" mais des choses différentes ?
-> Les traductions françaises, il semblerait, traduisent indirectement Jérôme plutôt que le grec en se copiant les uns sur les autres depuis Lefèvre exclut qui a "ire" (cf. Jérôme). C'est une explication [que je trouve tout à fait plausible]. A cela on a néanmoins en exception la traduction Parole Vivante (cette traduction étant unique en son genre, elle se différencie des autres de manière générale) en Eph 4:31 qui a : "Faites disparaître du milieu de vous toute mauvaise humeur".

**Comment by kylak** [comment]
Et de là, je proposerais peut-être pour ἐπιθυμέω : "être d'humeur à avoir" ? "mettre son humeur à avoir" ?

**Comment by nouveautestament** [comment]
Ajouté dans le minidico.
Ajouté dans le dictionnaire.

**Comment by kylak** [comment]
ΕDIT : Jc 5:13 "ευθυμει τις;"

ευθυμει: bonne humeur ? c'est effectivement ce que semble bien mettre le LSJ : "to be of good cheer". D'ailleurs, c'est ainsi que traduit la traduction "Monde Nouveau".
