### ISSUE TITLE
notes concernant l'aoriste

### ISSUE THREAD

**Issue by kylak** [nouveautestament/nouveautestament.github.io#4]
au lieu de mettre [ponctuellement] pour l'aoriste, mettre plutôt [à un moment donné] ?
exemple : 
au lieu de :
Éjecte la jeune servante et son fils, car qu'il n'hérite pas [ponctuellement] le fils de la jeune servante avec le fils de la libre.) Par conséquent, frères, nous ne sommes pas enfants de la jeune servante, mais de la libre.
avoir :
Éjecte la jeune servante et son fils, car à-un-moment-donné-qu'il-n-hérite-pas le fils de la jeune servante avec le fils de la libre.) Par conséquent, frères, nous ne sommes pas enfants de la jeune servante, mais de la libre.
?

**Comment by nouveautestament** [comment]
Trop d'ajouts.
