### ISSUE TITLE
Proposition de traduction Éphésiens 5:33 verbe effrayer

### ISSUE THREAD

**Issue by kylak** [nouveautestament/nouveautestament.github.io#5]
Le verbe est au passif, non à l'actif.

De plus, après vérification, la morphologie sous la R.P est fausse à ma connaissance, en ce que φοβεω n'est pas déponent de ce que j'ai pu voir et comprendre.

**Comment by nouveautestament** [comment]
> Le verbe est au passif, non à l'actif.

Le verbe est moyen-passif, médiopassif, selon Robinson aussi déponent.
Voyez donc avec Robinson s'il est déponent ou non.

**Comment by kylak** [comment]
Non il n'est pas déponent. Quelle sont vos sources pour affirmer cela ?

**Comment by nouveautestament** [comment]
https://github.com/byztxt/robinson-documentation/blob/master/doc/PARSING.COD#L67C25-L67C51
https://github.com/byztxt/greektext-antoniades/blob/master/parsed/EPH.UAN#L720C44-L720C52

**Comment by kylak** [comment]
Merci une vérification de la part de M.Robinson devrait se faire (https://github.com/byztxt/byzantine-majority-text/issues/27).
Cordialement.

**Comment by nouveautestament** [comment]
Robinson s'est trompé sur sa morphologie, il s'est aussi trompé sur son texte Grec.

**Comment by nouveautestament** [comment]
![image](https://github.com/nouveautestament/nouveautestament.github.io/assets/84104408/109c3230-6a5b-46d7-9f4c-9bdf1a165956)

https://github.com/byztxt/byzantine-majority-text/issues/27#issuecomment-1627918753

**Comment by nouveautestament** [comment]
Si Monsieur Robinson parle de "respect", s'il ne sait pas traduire un mot Grec "effrayer", 
comment peut-il donc établir un texte tout entier...
Selon toi Kylak, Robinson se trompe et dans la morphologie et dans la traduction.
Son texte Grec n'est donc pas à statuer confiant.

**Comment by kylak** [comment]
Qui n'a jamais fauté ?

**Comment by nouveautestament** [comment]
https://github.com/nouveautestament/nouveautestament.github.io/commit/a151c6f335fe9afe800a90b37f2964fed06467bb
