### ISSUE TITLE
Versions lemmatisées

### ISSUE THREAD

**Issue by SphRbtHyk** [nouveautestament/nouveautestament.github.io#9]
Bonjour, et merci pour votre énorme travail.

Comptez vous ajouter les versions lémmatisées des textes en latin/grec ?

En vous remerciant.

**Comment by nouveautestament** [comment]
Il y a deux versions lemmatisées en Romain, quatre en Héllène.
https://nouveautestament.github.io/interlineaire/technique/1-1.html

Accessibles dans le répertoire database.
https://github.com/nouveautestament/nouveautestament.github.io/tree/main/database/te

Ce travail est sur-tout pour donner une traduction fidèle, de l'Héllène envers le Français.
Vous avez mon email et mon numéro si besoin.
